import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { ArrowUpRight, BellRing, Check, ChevronRight, FileCheck2, FilePenLine, HeartHandshake, LockKeyhole, Plus, Scale, Settings2, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";

const docs = [
  { title: "Ontario will", type: "Personal document", progress: 72, status: "In progress", tone: "red" },
  { title: "Prenuptial agreement", type: "Shared workspace", progress: 18, status: "Not started", tone: "black" },
];

export default function Dashboard() {
  const { user, loading, logout } = useAuth({ redirectOnUnauthenticated: true });
  if (loading || !user) return <div className="flex min-h-screen items-center justify-center bg-[#fdfdfb] font-mono text-[10px] uppercase tracking-[0.14em]">Opening your private planning space…</div>;
  return <div className="min-h-screen bg-[#fdfdfb] text-[#101010]">
    <header className="border-b border-black/15 bg-[#fdfdfb]"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-5 lg:px-12"><Link href="/" className="flex items-center gap-3"><span className="brand-mark" /><span className="font-mono text-sm font-bold uppercase tracking-[0.24em]">Legacyloom</span></Link><div className="flex items-center gap-4"><span className="hidden font-mono text-[10px] uppercase tracking-[0.14em] text-black/45 sm:block">Ontario / Personal space</span><button className="flex h-9 w-9 items-center justify-center border border-black/15" aria-label="Account settings"><Settings2 className="h-4 w-4" /></button><button onClick={() => void logout()} className="hidden font-mono text-[10px] uppercase tracking-[0.12em] text-black/45 hover:text-[#e6332a] sm:block">Log out</button><div className="flex h-9 w-9 items-center justify-center bg-black text-xs font-bold text-white">AM</div></div></div></header>
    <main className="mx-auto max-w-[1440px] px-5 py-10 lg:px-12 lg:py-16">
      <div className="flex flex-col justify-between gap-8 border-b border-black pb-10 md:flex-row md:items-end"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-[#e6332a]">Personal dashboard / 01</p><h1 className="mt-6 text-6xl font-black leading-[0.86] tracking-[-0.08em] md:text-8xl">Good morning,<br />Alex<span className="text-[#e6332a]">.</span></h1><p className="mt-7 max-w-md text-base leading-7 text-black/60">Your planning space is here. Pick up where you left off, or start a new document.</p></div><Button className="h-12 rounded-none bg-[#e6332a] px-6 text-xs font-bold uppercase tracking-[0.14em] text-white shadow-none hover:bg-black"><Plus className="mr-2 h-4 w-4" /> New document</Button></div>
      <section className="grid border-b border-black/15 lg:grid-cols-[0.66fr_0.34fr]"><div className="border-b border-black/15 py-10 lg:border-b-0 lg:border-r lg:pr-12"><div className="flex items-center justify-between"><h2 className="text-2xl font-bold tracking-[-0.04em]">Your documents</h2><Link href="/vault" className="font-mono text-[10px] font-bold uppercase tracking-[0.14em] hover:text-[#e6332a]">Open vault <ArrowUpRight className="ml-1 inline h-3 w-3" /></Link></div><div className="mt-8 space-y-3">{docs.map((doc) => <div key={doc.title} className="group border border-black/15 bg-white p-5 transition hover:border-black"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-4"><div className={`flex h-11 w-11 items-center justify-center ${doc.tone === "red" ? "bg-[#e6332a] text-white" : "bg-black text-white"}`}><FilePenLine className="h-5 w-5" /></div><div><h3 className="font-bold">{doc.title}</h3><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.12em] text-black/45">{doc.type}</p></div></div><ChevronRight className="h-5 w-5 text-black/35 transition-transform group-hover:translate-x-1" /></div><div className="mt-6 flex items-center gap-4"><div className="h-1.5 flex-1 bg-black/10"><div className={`h-full ${doc.tone === "red" ? "bg-[#e6332a]" : "bg-black"}`} style={{ width: `${doc.progress}%` }} /></div><span className="font-mono text-[10px] font-bold">{doc.progress}%</span></div><div className="mt-3 flex items-center justify-between font-mono text-[10px] uppercase tracking-[0.1em] text-black/45"><span>{doc.status}</span><span>Updated today</span></div></div>)}</div></div><aside className="py-10 lg:pl-12"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center bg-[#e6332a] text-white"><BellRing className="h-5 w-5" /></div><div><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-black/45">Reminders</p><p className="font-bold">Opt-in only</p></div></div><p className="mt-7 text-sm leading-6 text-black/60">You have reminders turned off. Turn them on if you want help finishing your documents or reviewing them after a major life change.</p><Button variant="outline" className="mt-6 w-full rounded-none border-black text-xs font-bold uppercase tracking-[0.12em]">Manage reminders</Button></aside></section>
      <section className="grid border-b border-black/15 md:grid-cols-3"><div className="border-b border-black/15 p-7 md:border-b-0 md:border-r md:p-10"><div className="flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-black/45">Readiness</p><Scale className="h-5 w-5" /></div><p className="mt-8 text-5xl font-black tracking-[-0.07em]">3<span className="text-[#e6332a]">/</span>5</p><p className="mt-3 text-sm leading-6 text-black/55">Your will has three key sections ready for review.</p></div><div className="border-b border-black/15 p-7 md:border-b-0 md:border-r md:p-10"><div className="flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-black/45">Review status</p><FileCheck2 className="h-5 w-5" /></div><p className="mt-8 text-2xl font-black tracking-[-0.04em]">Self-review next</p><p className="mt-3 text-sm leading-6 text-black/55">Review your choices before preparing the signing copy.</p><button className="mt-6 font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-[#e6332a]">Continue review <ArrowUpRight className="ml-1 inline h-3 w-3" /></button></div><div className="p-7 md:p-10"><div className="flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-black/45">Privacy check</p><LockKeyhole className="h-5 w-5" /></div><p className="mt-8 text-2xl font-black tracking-[-0.04em]">All clear</p><p className="mt-3 text-sm leading-6 text-black/55">Your documents are stored in your private vault. No reminders are sent without consent.</p><button className="mt-6 font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-[#e6332a]">View privacy settings <ArrowUpRight className="ml-1 inline h-3 w-3" /></button></div></section>
      <section className="grid gap-8 py-10 lg:grid-cols-[0.68fr_0.32fr]"><div><div className="flex items-center justify-between"><h2 className="text-2xl font-bold tracking-[-0.04em]">Your next steps</h2><span className="font-mono text-[10px] uppercase tracking-[0.14em] text-black/45">3 actions</span></div><div className="mt-6 divide-y divide-black/15 border-y border-black/15">{[["Complete your executor choices","Will / Section 04","In progress"],["Read the signing instructions","Will / Before you sign","Ready"],["Invite your partner","Prenup / Shared workspace","Not started"]].map(([title,meta,status], index) => <div key={title} className="flex items-center gap-4 py-5"><span className="font-mono text-xs text-[#e6332a]">0{index + 1}</span><div className="flex-1"><p className="font-bold">{title}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.1em] text-black/45">{meta}</p></div><span className="hidden font-mono text-[10px] uppercase tracking-[0.1em] text-black/45 sm:block">{status}</span><ChevronRight className="h-4 w-4" /></div>)}</div></div><div className="bg-[#101010] p-7 text-white lg:p-9"><HeartHandshake className="h-5 w-5 text-[#ff554b]" /><h3 className="mt-10 text-3xl font-black leading-[0.92] tracking-[-0.06em]">Give someone else a head start.</h3><p className="mt-5 text-sm leading-6 text-white/55">Optional donations keep Legacyloom free for people who need it.</p><Button className="mt-8 w-full rounded-none bg-[#e6332a] text-xs font-bold uppercase tracking-[0.12em] text-white shadow-none hover:bg-white hover:text-black">Make a donation</Button></div></section>
      <div className="flex items-start gap-3 border-t border-black/15 pt-6"><UserRound className="mt-0.5 h-4 w-4" /><p className="max-w-2xl text-xs leading-5 text-black/50"><strong className="text-black">Remember:</strong> Legacyloom is software, not legal advice. If your situation is complex or you are prompted to seek independent legal advice, pause here and speak with a qualified Ontario lawyer.</p></div>
    </main>
  </div>;
}
