import { useState } from "react";
import { startLogin } from "@/const";
import {
  ArrowRight,
  Check,
  ChevronDown,
  CircleHelp,
  FileCheck2,
  FilePenLine,
  HeartHandshake,
  LockKeyhole,
  Menu,
  Scale,
  ShieldCheck,
  Sparkles,
  UsersRound,
  X,
} from "lucide-react";
import { Button } from "@/components/ui/button";

const navItems = ["Why Legacyloom", "How it works", "For professionals", "Learn"];

const features = [
  { number: "01", icon: FilePenLine, title: "Make a will", body: "A guided, Ontario-first flow that turns your wishes into a clear draft you can review, update, and prepare to sign.", cta: "Start a will" },
  { number: "02", icon: UsersRound, title: "Plan together", body: "Build a prenuptial agreement with shared intake, financial disclosure prompts, and an independent legal advice checkpoint for each person.", cta: "Explore prenups" },
  { number: "03", icon: HeartHandshake, title: "Keep it current", body: "Store versions securely, capture life changes, and get reminders only when you choose to receive them.", cta: "See the vault" },
];

function BrandMark() {
  return <div className="flex items-center gap-3" aria-label="Legacyloom home"><span className="brand-mark" aria-hidden="true" /><span className="font-mono text-sm font-bold uppercase tracking-[0.24em]">Legacyloom</span></div>;
}

export default function Home() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [faqOpen, setFaqOpen] = useState<number | null>(0);
  return (
    <div className="min-h-screen bg-[#fdfdfb] text-[#101010] selection:bg-[#e6332a] selection:text-white">
      <header className="border-b border-black/15 bg-[#fdfdfb]/95 backdrop-blur-sm"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-5 lg:px-12"><BrandMark /><nav className="hidden items-center gap-8 text-[11px] font-bold uppercase tracking-[0.15em] md:flex" aria-label="Primary navigation">{navItems.map((item) => <a key={item} href={`#${item.toLowerCase().replaceAll(" ", "-")}`} className="transition-colors hover:text-[#e6332a]">{item}</a>)}<a href="#pricing" className="transition-colors hover:text-[#e6332a]">Pricing</a></nav><div className="hidden items-center gap-3 md:flex"><Button variant="ghost" onClick={() => startLogin()} className="rounded-none px-4 text-xs font-bold uppercase tracking-[0.12em]">Log in</Button><Button onClick={() => startLogin()} className="rounded-none bg-[#e6332a] px-5 text-xs font-bold uppercase tracking-[0.12em] text-white shadow-none hover:bg-black">Get started <ArrowRight className="ml-2 h-4 w-4" /></Button></div><button className="md:hidden" onClick={() => setMobileOpen(!mobileOpen)} aria-label={mobileOpen ? "Close menu" : "Open menu"}>{mobileOpen ? <X /> : <Menu />}</button></div>{mobileOpen && <div className="border-t border-black/15 px-5 py-4 md:hidden"><div className="flex flex-col gap-4 text-xs font-bold uppercase tracking-[0.15em]">{navItems.map((item) => <a key={item} href={`#${item.toLowerCase().replaceAll(" ", "-")}`} onClick={() => setMobileOpen(false)}>{item}</a>)}<Button onClick={() => startLogin()} className="mt-2 w-full rounded-none bg-[#e6332a] text-white">Get started</Button></div></div>}</header>
      <main>
        <section className="grid min-h-[650px] border-b border-black/15 lg:grid-cols-[1.05fr_0.95fr]" id="why-legacyloom"><div className="flex flex-col justify-between border-r-0 border-black/15 px-5 py-16 lg:border-r lg:px-12 lg:py-20"><div><div className="mb-12 flex items-start justify-between gap-8"><p className="max-w-[220px] font-mono text-[10px] font-bold uppercase leading-relaxed tracking-[0.18em] text-black/55">Ontario's nonprofit digital service for the documents that help protect the people you love.</p><span className="red-square hidden lg:block" aria-hidden="true" /></div><h1 className="max-w-3xl text-[clamp(3.4rem,7vw,7.6rem)] font-black leading-[0.87] tracking-[-0.08em]">A clearer way<br />to plan ahead<span className="text-[#e6332a]">.</span></h1><p className="mt-10 max-w-lg text-lg leading-relaxed text-black/65">Make an Ontario will or prenup with plain-language guidance, thoughtful checkpoints, and no pressure to pay. <strong>The software is not legal advice.</strong></p></div><div className="mt-16 flex flex-col gap-5 sm:flex-row sm:items-center"><Button className="h-14 rounded-none bg-[#e6332a] px-7 text-sm font-bold uppercase tracking-[0.13em] text-white shadow-none hover:bg-black">Check if we're right for you <ArrowRight className="ml-3 h-4 w-4" /></Button><a className="group flex items-center gap-2 text-xs font-bold uppercase tracking-[0.13em]" href="#how-it-works">See how it works <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></a></div></div><div className="relative flex min-h-[460px] items-end overflow-hidden bg-[#dfe4df] p-5 lg:min-h-0 lg:p-12"><div className="absolute inset-0 opacity-70" style={{ backgroundImage: "linear-gradient(130deg, transparent 0 55%, rgba(255,255,255,.5) 55% 56%, transparent 56%), repeating-linear-gradient(90deg, transparent 0 64px, rgba(0,0,0,.045) 64px 65px), repeating-linear-gradient(0deg, transparent 0 64px, rgba(0,0,0,.045) 64px 65px)" }} /><div className="relative z-10 w-full max-w-[500px] border border-black bg-[#fdfdfb] p-7 shadow-[18px_18px_0_#e6332a] lg:p-10"><div className="mb-10 flex items-center justify-between border-b border-black pb-4"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.18em]">The Legacyloom promise</span><ShieldCheck className="h-5 w-5" /></div><div className="space-y-7">{["Free or pay what you can", "Ontario-specific by design", "Your documents stay yours"].map((item, index) => <div key={item} className="flex items-start gap-4"><span className="font-mono text-xs text-[#e6332a]">0{index + 1}</span><span className="text-xl font-semibold tracking-tight">{item}</span></div>)}</div><div className="mt-10 border-t border-black pt-4 font-mono text-[10px] uppercase tracking-[0.16em] text-black/55">Built for access. Built for trust.</div></div></div></section>
        <section className="border-b border-black/15" id="how-it-works"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-[0.32fr_0.68fr]"><div className="border-b border-black/15 px-5 py-12 lg:border-b-0 lg:border-r lg:px-12"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-[#e6332a]">01 / The service</p><h2 className="mt-8 max-w-xs text-4xl font-black leading-[0.95] tracking-[-0.06em]">Simple where it can be. Serious where it matters.</h2></div><div className="grid md:grid-cols-3">{features.map(({ number, icon: Icon, title, body, cta }) => <article key={title} className="border-b border-black/15 p-7 last:border-b-0 md:border-b-0 md:border-r md:p-10 md:last:border-r-0"><div className="flex items-center justify-between"><span className="font-mono text-[10px] text-[#e6332a]">{number}</span><Icon className="h-5 w-5" strokeWidth={1.5} /></div><h3 className="mt-16 text-2xl font-bold tracking-[-0.04em]">{title}</h3><p className="mt-5 text-sm leading-6 text-black/60">{body}</p><a href="#get-started" className="mt-10 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.15em] hover:text-[#e6332a]">{cta} <ArrowRight className="h-3 w-3" /></a></article>)}</div></div></section>
        <section className="bg-[#101010] text-white" id="get-started"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-[0.7fr_0.3fr]"><div className="border-b border-white/20 px-5 py-16 lg:border-b-0 lg:border-r lg:px-12 lg:py-24"><div className="flex items-start justify-between"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-[#ff554b]">02 / Start with fit</p><span className="red-square" /></div><h2 className="mt-16 max-w-4xl text-5xl font-black leading-[0.9] tracking-[-0.07em] md:text-7xl">Before the paperwork,<br /><span className="text-[#ff554b]">start with your situation.</span></h2><p className="mt-10 max-w-xl text-lg leading-relaxed text-white/60">Our eligibility and suitability screener helps you understand whether a guided digital flow is a reasonable starting point—or whether you should speak with a qualified Ontario legal professional first.</p><Button className="mt-10 h-14 rounded-none bg-white px-7 text-xs font-bold uppercase tracking-[0.14em] text-black hover:bg-[#ff554b] hover:text-white">Take the 2-minute screener <ArrowRight className="ml-3 h-4 w-4" /></Button></div><div className="flex flex-col justify-between px-5 py-12 lg:px-10 lg:py-16"><div className="space-y-7">{["Ontario residents and Ontario legal context only.", "Complex or out-of-scope situations are routed to professional review.", "You can stop, save, or ask for help at any point."].map((item) => <div key={item} className="flex gap-3"><Check className="mt-1 h-4 w-4 text-[#ff554b]" /><p className="text-sm leading-6 text-white/75">{item}</p></div>)}</div><p className="font-mono text-[10px] uppercase leading-relaxed tracking-[0.14em] text-white/35">Not a law firm. Not a substitute for legal advice. Always review the signing instructions and seek independent legal advice when prompted.</p></div></div></section>
        <section className="border-b border-black/15" id="pricing"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-[0.35fr_0.65fr]"><div className="border-b border-black/15 px-5 py-14 lg:border-b-0 lg:border-r lg:px-12"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-[#e6332a]">03 / A different model</p><h2 className="mt-8 text-5xl font-black leading-[0.9] tracking-[-0.07em]">Access is the point.</h2></div><div className="grid md:grid-cols-2"><div className="border-b border-black/15 p-7 md:border-b-0 md:border-r md:p-12"><Sparkles className="h-5 w-5" /><h3 className="mt-10 text-2xl font-bold tracking-[-0.04em]">Free by default</h3><p className="mt-5 text-sm leading-6 text-black/60">Core planning tools stay available without a paywall. If you can contribute, choose an amount that works for you. If you cannot, continue anyway.</p><Button variant="outline" className="mt-9 rounded-none border-black px-5 text-xs font-bold uppercase tracking-[0.12em] hover:bg-black hover:text-white">How funding works</Button></div><div className="p-7 md:p-12"><HeartHandshake className="h-5 w-5" /><h3 className="mt-10 text-2xl font-bold tracking-[-0.04em]">Give forward</h3><p className="mt-5 text-sm leading-6 text-black/60">Optional one-time donations help subsidize professional review, translation, and access for people facing barriers.</p><Button className="mt-9 rounded-none bg-[#e6332a] px-5 text-xs font-bold uppercase tracking-[0.12em] text-white shadow-none hover:bg-black">Support the mission</Button></div></div></div></section>
        <section className="border-b border-black/15 bg-[#f1f0ec]" id="learn"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-[0.45fr_0.55fr]"><div className="border-b border-black/15 px-5 py-14 lg:border-b-0 lg:border-r lg:px-12"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-[#e6332a]">04 / Trust by design</p><h2 className="mt-8 max-w-lg text-5xl font-black leading-[0.9] tracking-[-0.07em]">Your private plans should feel private.</h2><p className="mt-8 max-w-md text-base leading-7 text-black/60">We collect only what the service needs, explain why we ask, and make reminders opt-in. Drafts and final versions are kept in a secure vault with a visible history of changes.</p></div><div className="grid sm:grid-cols-2">{[[LockKeyhole,"Privacy, in plain language","No selling personal information. No silent reminders. No confusing defaults."],[Scale,"Legal guardrails","Suitability checks, signing instructions, and independent legal advice prompts are built into the journey."],[CircleHelp,"Learn as you go","Short, accessible explanations help you make informed choices without pretending the software is your lawyer."],[FileCheck2,"A clear next step","Every dashboard state ends with an action: continue, review, sign, update, or ask for help."]].map(([Icon,title,body]) => <div key={String(title)} className="border-b border-black/15 p-7 sm:p-12"><Icon className="h-5 w-5" /><h3 className="mt-8 text-xl font-bold">{String(title)}</h3><p className="mt-4 text-sm leading-6 text-black/60">{String(body)}</p></div>)}</div></div></section>
        <section className="border-b border-black/15"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-[0.28fr_0.72fr]"><div className="border-b border-black/15 px-5 py-12 lg:border-b-0 lg:border-r lg:px-12"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-[#e6332a]">Questions</p><h2 className="mt-8 text-4xl font-black leading-[0.95] tracking-[-0.06em]">No fine print hiding here.</h2></div><div>{["Is Legacyloom a law firm?", "What happens when my situation is complex?", "Can I update my documents later?"].map((question, index) => <div key={question} className="border-b border-black/15 last:border-b-0"><button className="flex w-full items-center justify-between px-5 py-7 text-left text-lg font-bold tracking-[-0.03em] lg:px-12" onClick={() => setFaqOpen(faqOpen === index ? null : index)}>{question}<ChevronDown className={`h-5 w-5 transition-transform ${faqOpen === index ? "rotate-180" : ""}`} /></button>{faqOpen === index && <p className="max-w-2xl px-5 pb-8 text-sm leading-7 text-black/60 lg:px-12">Legacyloom is software, not a law firm, and it does not provide legal advice. We explain what the flow can handle, flag situations that may need professional help, and include clear checkpoints before you rely on a document.</p>}</div>)}</div></div></section>
        <section className="bg-[#e6332a] px-5 py-16 text-white lg:px-12 lg:py-24"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-10 md:flex-row md:items-end"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-white/70">Built for Ontario. Built for everyone.</p><h2 className="mt-8 max-w-3xl text-5xl font-black leading-[0.88] tracking-[-0.07em] md:text-7xl">Start with the plan.<br />Keep the people.</h2></div><Button onClick={() => startLogin()} className="h-14 rounded-none bg-black px-7 text-xs font-bold uppercase tracking-[0.14em] text-white shadow-none hover:bg-white hover:text-black">Create your free account <ArrowRight className="ml-3 h-4 w-4" /></Button></div></section>
      </main>
      <footer className="bg-[#101010] px-5 py-12 text-white lg:px-12"><div className="mx-auto grid max-w-[1440px] gap-12 md:grid-cols-[1fr_auto_auto_auto]"><div><BrandMark /><p className="mt-6 max-w-xs text-sm leading-6 text-white/45">A nonprofit digital service for essential legal planning in Ontario.</p></div><div><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-white/35">Explore</p><div className="mt-5 flex flex-col gap-3 text-sm text-white/70"><a href="#why-legacyloom">Why Legacyloom</a><a href="#how-it-works">How it works</a><a href="#learn">Learn</a></div></div><div><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-white/35">Support</p><div className="mt-5 flex flex-col gap-3 text-sm text-white/70"><a href="#get-started">Eligibility</a><a href="#pricing">Donate</a><a href="#learn">Privacy</a></div></div><div><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-white/35">Legal</p><p className="mt-5 max-w-[210px] text-xs leading-5 text-white/45">Software is not legal advice. Have a qualified Ontario lawyer review anything consequential.</p></div></div><div className="mx-auto mt-12 flex max-w-[1440px] justify-between border-t border-white/15 pt-5 font-mono text-[10px] uppercase tracking-[0.1em] text-white/35"><span>© 2026 Legacyloom</span><span>Ontario, Canada</span></div></footer>
    </div>
  );
}
