import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CircleAlert, FilePenLine, Info, LockKeyhole, Scale, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { isSuitabilityComplete, suitabilityQuestions } from "@shared/planner";

const willSteps = ["Suitability", "Your people", "Your wishes", "Review & sign"];
const prenupSteps = ["Suitability", "Together", "Disclosure", "Legal advice"];

export default function Planner() {
  const [kind, setKind] = useState<"will" | "prenup">("will");
  const [step, setStep] = useState(0);
  const [screened, setScreened] = useState(false);
  const [screenChecks, setScreenChecks] = useState([false, false, false]);
  const [saved, setSaved] = useState(false);
  const steps = kind === "will" ? willSteps : prenupSteps;
  useEffect(() => {
    try {
      const savedPlan = JSON.parse(localStorage.getItem("legacyloom-planner-progress") || "null");
      if (savedPlan?.kind === "will" || savedPlan?.kind === "prenup") setKind(savedPlan.kind);
      if (Number.isInteger(savedPlan?.step)) setStep(Math.max(0, Math.min(3, savedPlan.step)));
      if (Array.isArray(savedPlan?.screenChecks) && savedPlan.screenChecks.length === 3) setScreenChecks(savedPlan.screenChecks);
    } catch { /* ignore unavailable local storage */ }
  }, []);
  const saveProgress = (nextStep: number) => {
    localStorage.setItem("legacyloom-planner-progress", JSON.stringify({ kind, step: nextStep, screenChecks }));
    setSaved(true);
    window.setTimeout(() => setSaved(false), 1600);
  };
  const isFinal = step === steps.length - 1;
  return <div className="min-h-screen bg-[#fdfdfb] text-[#101010]">
    <header className="border-b border-black/15"><div className="mx-auto flex max-w-[1200px] items-center justify-between px-5 py-5 lg:px-10"><Link href="/" className="flex items-center gap-3"><span className="brand-mark" /><span className="font-mono text-sm font-bold uppercase tracking-[0.24em]">Legacyloom</span></Link><span className="font-mono text-[10px] uppercase tracking-[0.14em] text-black/45">Ontario / New plan</span></div></header>
    <main className="mx-auto max-w-[1200px] px-5 py-10 lg:px-10 lg:py-16">
      <div className="flex flex-col justify-between gap-5 border-b border-black pb-8 md:flex-row md:items-end"><div><Link href="/dashboard" className="font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-[#e6332a]">← Back to dashboard</Link><h1 className="mt-8 text-5xl font-black leading-[0.88] tracking-[-0.07em] md:text-7xl">Let's make a plan<span className="text-[#e6332a]">.</span></h1></div><div className="max-w-xs text-right font-mono text-[10px] uppercase leading-relaxed tracking-[0.12em] text-black/45">Your progress is saved as you go. You can pause at any time.</div></div>
      <div className="mt-8 grid gap-8 lg:grid-cols-[0.25fr_0.75fr]"><aside className="border-b border-black/15 pb-8 lg:border-b-0 lg:border-r lg:pb-0 lg:pr-8"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-black/45">Choose a document</p><div className="mt-5 space-y-2"><button onClick={() => { setKind("will"); setStep(0); }} className={`flex w-full items-center gap-3 border p-4 text-left ${kind === "will" ? "border-black bg-black text-white" : "border-black/15 hover:border-black"}`}><FilePenLine className="h-5 w-5" /><span><span className="block font-bold">Ontario will</span><span className={`mt-1 block text-xs ${kind === "will" ? "text-white/55" : "text-black/45"}`}>For your estate wishes</span></span></button><button onClick={() => { setKind("prenup"); setStep(0); }} className={`flex w-full items-center gap-3 border p-4 text-left ${kind === "prenup" ? "border-black bg-black text-white" : "border-black/15 hover:border-black"}`}><UsersRound className="h-5 w-5" /><span><span className="block font-bold">Prenuptial agreement</span><span className={`mt-1 block text-xs ${kind === "prenup" ? "text-white/55" : "text-black/45"}`}>For a shared conversation</span></span></button></div><div className="mt-10 border-t border-black/15 pt-7"><div className="flex items-start gap-3"><LockKeyhole className="mt-0.5 h-4 w-4" /><p className="text-xs leading-5 text-black/55">Private by default. This is software, not legal advice. Your answers are only used to prepare your planning workspace.</p></div></div></aside>
        <section><div className="grid grid-cols-4 border-y border-black/15">{steps.map((label, index) => <div key={label} className={`border-r border-black/15 p-3 last:border-r-0 ${index === step ? "bg-[#e6332a] text-white" : ""}`}><span className="font-mono text-[10px]">0{index + 1}</span><p className="mt-3 hidden text-[10px] font-bold uppercase tracking-[0.1em] sm:block">{label}</p></div>)}</div><div className="mt-10 max-w-2xl">{step === 0 && <div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-[#e6332a]">Step 01 / Start with fit</p><h2 className="mt-6 text-4xl font-black leading-[0.9] tracking-[-0.06em]">A quick check before we begin.</h2><p className="mt-6 text-base leading-7 text-black/60">This service is designed for people planning within Ontario who can understand the questions and review their documents. It is not designed for urgent, contested, or highly complex situations.</p><div className="mt-8 space-y-3">{suitabilityQuestions.map((q, index) => <label key={q} className="flex items-start gap-3 border border-black/15 p-4 text-sm leading-6"><input type="checkbox" className="mt-1 accent-[#e6332a]" checked={screenChecks[index]} onChange={(e) => { const next = [...screenChecks]; next[index] = e.target.checked; setScreenChecks(next); setScreened(isSuitabilityComplete(next)); }} /><span>{q}</span></label>)}</div>{screened && <div className="mt-5 flex gap-3 border border-[#e6332a] bg-[#fff4f3] p-4 text-sm leading-6"><Info className="mt-0.5 h-4 w-4 text-[#e6332a]" /><span>Suitability is a starting point, not a legal conclusion. You can still stop and ask for professional help.</span></div>}</div>}
          {step === 1 && kind === "will" && <div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-[#e6332a]">Step 02 / Your people</p><h2 className="mt-6 text-4xl font-black leading-[0.9] tracking-[-0.06em]">Who should help carry out your wishes?</h2><p className="mt-6 text-base leading-7 text-black/60">Choose people you trust as your executor and backup executor. You will be able to review every choice later.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><label className="border border-black/15 p-5"><span className="font-mono text-[10px] uppercase tracking-[0.12em] text-black/45">Primary executor</span><input className="mt-4 w-full border-b border-black bg-transparent py-2 text-lg outline-none" placeholder="Full name" /></label><label className="border border-black/15 p-5"><span className="font-mono text-[10px] uppercase tracking-[0.12em] text-black/45">Backup executor</span><input className="mt-4 w-full border-b border-black bg-transparent py-2 text-lg outline-none" placeholder="Full name" /></label></div></div>}
          {step === 1 && kind === "prenup" && <div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-[#e6332a]">Step 02 / Together</p><h2 className="mt-6 text-4xl font-black leading-[0.9] tracking-[-0.06em]">Make space for two people.</h2><p className="mt-6 text-base leading-7 text-black/60">You can start alone, then invite your partner into a shared workspace. Each person should review their own choices independently.</p><div className="mt-8 border border-black p-5"><div className="flex items-center gap-3"><UsersRound className="h-5 w-5" /><span className="font-bold">Shared workspace</span></div><p className="mt-5 text-sm leading-6 text-black/60">Invite links will never reveal your financial answers to the other person unless you choose to share them.</p><Button variant="outline" className="mt-6 rounded-none border-black text-xs font-bold uppercase tracking-[0.12em]">Invite partner later</Button></div></div>}
          {step === 2 && kind === "will" && <div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-[#e6332a]">Step 03 / Your wishes</p><h2 className="mt-6 text-4xl font-black leading-[0.9] tracking-[-0.06em]">What matters most to you?</h2><p className="mt-6 text-base leading-7 text-black/60">We will work through beneficiaries, personal items, charitable gifts, and guardianship questions in plain language.</p><div className="mt-8 space-y-3">{["I have minor children or dependants", "I want to leave a charitable gift", "I own a business or assets outside Ontario"].map((q) => <label key={q} className="flex items-center gap-3 border border-black/15 p-4 text-sm"><input type="checkbox" className="accent-[#e6332a]" /><span>{q}</span></label>)}</div></div>}
          {step === 2 && kind === "prenup" && <div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-[#e6332a]">Step 03 / Disclosure</p><h2 className="mt-6 text-4xl font-black leading-[0.9] tracking-[-0.06em]">Start with a complete picture.</h2><p className="mt-6 text-base leading-7 text-black/60">Financial disclosure is a key part of a fair process. Add assets, debts, income, and supporting documents. The service will flag gaps without deciding what your agreement should say.</p><div className="mt-8 flex gap-3 border border-[#e6332a] bg-[#fff4f3] p-4 text-sm leading-6"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0 text-[#e6332a]" /><span>Both people should provide honest, current disclosure and get independent legal advice before signing.</span></div><Button variant="outline" className="mt-6 rounded-none border-black text-xs font-bold uppercase tracking-[0.12em]">Add disclosure item</Button></div>}
          {step === 3 && <div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-[#e6332a]">Step 04 / {kind === "will" ? "Review & sign" : "Legal advice"}</p><h2 className="mt-6 text-4xl font-black leading-[0.9] tracking-[-0.06em]">{kind === "will" ? "Ready for a careful review." : "Independent advice is part of the plan."}</h2><p className="mt-6 text-base leading-7 text-black/60">{kind === "will" ? "Your draft will be available to preview and download. Follow the Ontario signing and witness instructions exactly, and ask a qualified lawyer if anything is unclear." : "Each person should have their own lawyer review the agreement and provide independent legal advice before signing. Legacyloom will keep this checkpoint visible until both people confirm it."}</p><div className="mt-8 border border-black bg-black p-6 text-white"><div className="flex items-start gap-3"><Scale className="mt-0.5 h-5 w-5 text-[#ff554b]" /><div><p className="font-bold">{kind === "will" ? "Signing checklist" : "Independent legal advice checkpoint"}</p><p className="mt-3 text-sm leading-6 text-white/60">{kind === "will" ? "Review the full document, print it, sign with the required witnesses, and store the signed original safely." : "Do not treat a shared workspace or software-generated draft as a substitute for separate legal advice."}</p><label className="mt-5 flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1 accent-[#e6332a]" /><span>I understand and will complete this checkpoint before relying on the document.</span></label></div></div></div></div>}
          <div className="mt-12 flex items-center justify-between border-t border-black/15 pt-6">{saved && <span className="font-mono text-[10px] uppercase tracking-[0.12em] text-[#e6332a]">Progress saved</span>}<Button variant="ghost" disabled={step === 0} onClick={() => setStep(Math.max(0, step - 1))} className="rounded-none text-xs font-bold uppercase tracking-[0.12em]"><ArrowLeft className="mr-2 h-4 w-4" /> Previous</Button><Button onClick={() => { const nextStep = Math.min(steps.length - 1, step + 1); saveProgress(nextStep); setStep(nextStep); }} disabled={step === 0 && !screened} className="rounded-none bg-[#e6332a] px-6 text-xs font-bold uppercase tracking-[0.12em] text-white shadow-none hover:bg-black">{isFinal ? "Save to vault" : "Save & continue"}<ArrowRight className="ml-2 h-4 w-4" /></Button></div></div>
        </section></div>
    </main>
  </div>;
}
